name: "Resharper InspectCode"
author: "Nick Badal"
description: "An action that runs the InspectCode CLI utility from JetBrains"
branding:
  icon: "bar-chart"
  color: "blue"
inputs:
  solution:
    description: "Path to your solution file, ex: MyProject.sln"
    required: true
  settings:
    description: "Path to your dotsettings file, ex: MyProject.DotSettings"
    required: false
  files:
    description: "Path to your files to analyze, ex: Interactor.cs"
    required: false
  projects:
    description: "list of projects to build"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.solution }}
    - "-o=report.xml"
    - "--profile=${{ inputs.settings }}"
    - "--include=${{ inputs.files }}"
    - "${{ inputs.projects }}"
